$(document).ready(function(){
  $('person').css({"background-color":"orange"});
  $('location').css({"background-color":"green"});
  $('organization').css({"background-color":"pink"});
  $('money').css({"background-color":"yellow"});
  $('miscellanea').css({"background-color":"purple"});
  $('phone').css({"background-color":"gray"});
  $('interesting').css({"background-color":"red"});
  $('date').css({"background-color":"blue"});
});